### ISSUE TITLE
Not able to run it. ON Linux (Ubuntu 18.04)

### ISSUE THREAD

**Issue by isinghmitesh** [KalleHallden/AutoTimer#1]
**ERROR:**

`Traceback (most recent call last):
  File "autotimer.py", line 2, in <module>
    from AppKit import NSWorkspace
ImportError: No module named AppKit
`

> selenium and AppKit are installed. Still, it's not working. Please help.

**Comment by KalleHallden** [comment]
I had this issue as well, try running this pip install -U pyobjc but not in
a virtual environment

Hope this helps :)

**Comment by isinghmitesh** [comment]
Hi KalleHallden,
First of all thanks for replying, :) I like all your style of coding and I must say you have awesome projects. Can't appreciate enough your efforts. Kudos to you.

**Comment by isinghmitesh** [comment]
Hi again, I tried 'pip install -U pyobjc' but it gives some error that SystemVersion.plist is missing.

`IOError: [Errno 2] No such file or directory: '/System/Library/CoreServices/SystemVersion.plist'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

I will try to find the fix by myself but in case you ran into it. Please help. I really really want to run this and see how much time I am spending on vs code while coding. :)

**Comment by KalleHallden** [comment]
Are you using Mac or windows or Linux?
Because this only works on Mac :)

**Comment by isinghmitesh** [comment]
i m using Linux.
Linux fix: https://github.com/singhmitesh/AutoTimer

**Comment by KalleHallden** [comment]
Okay take a look at this then:

**Comment by isinghmitesh** [comment]
Let's see if I can fix it. Let's collaborate on some projects. I would love to work with you. What do you say ?

**Comment by amitjslearn** [comment]
> **ERROR:**
> 
> `Traceback (most recent call last): File "autotimer.py", line 2, in <module> from AppKit import NSWorkspace ImportError: No module named AppKit `
> 
> > selenium and AppKit are installed. Still, it's not working. Please help.

Hey! how did you install AppKit? I am getting errors. I tried with both pip and pip2, help much-appreciated.
![14](https://user-images.githubusercontent.com/27467368/63638686-4b808f80-c6a9-11e9-9a3d-f8db8a44c871.png)
![2](https://user-images.githubusercontent.com/27467368/63638689-4f141680-c6a9-11e9-9fb6-9791b2ad438c.png)
![3](https://user-images.githubusercontent.com/27467368/63638694-54716100-c6a9-11e9-8701-7b45bb75a8b5.png)
![4](https://user-images.githubusercontent.com/27467368/63638695-54716100-c6a9-11e9-89ab-a8dfe7ecc45a.png)

**Comment by isinghmitesh** [comment]
hi @amitjslearn,
I think Appkit is just for Mac and I might have got some other package. But don't worry, I m working on the version which will work on Linux. KalleHallden's build is just for Mac. Of course, we will have to get the active window differently for Linux.

**Comment by amitjslearn** [comment]
> hi @amitjslearn,
> I think Appkit is just for Mac and I might have got some other package. But don't worry, I m working on the version which will work on Linux. KalleHallden's build is just for Mac. Of course, we will have to get the active window differently for Linux.
Yeah after a lot of searching I got to know this. When will you post the Linux version? Need any help?

**Comment by amitjslearn** [comment]
> hi @amitjslearn,
> I think Appkit is just for Mac and I might have got some other package. But don't worry, I m working on the version which will work on Linux. KalleHallden's build is just for Mac. Of course, we will have to get the active window differently for Linux.

Yeah after a lot of searching I got to know this. When will you post the Linux version? Need any help?

**Comment by isinghmitesh** [comment]
i think i m 50% there, getting the active application in real time is working. Just need to hook up with the json file writing. Help would be much appriciated. But what should we do ? 
1> Create new Repo for Linux
2> Try to integrate Linux patch into this Repo itself ?

**Comment by amitjslearn** [comment]
> i think i m 50% there, getting the active application in real time is working. Just need to hook up with the json file writing. Help would be much appriciated. But what should we do ?
> 1> Create new Repo for Linux
> 2> Try to integrate Linux patch into this Repo itself ?

Create new Repo for Linux and put a link referencing new repo in the current repo and rename the current repo indicating its for mac. What do you think @singhmitesh  @KalleHallden  ?

**Comment by isinghmitesh** [comment]
I don't have privileges on the current repo. But I can create a new repo with KalleHallden's permission. 
@KalleHallden ? :)

**Comment by singhmitesh** [comment]
Working on Linux: [https://github.com/singhmitesh/AutoTimer](url)

**Comment by isinghmitesh** [comment]
Working on Linux: https://github.com/singhmitesh/AutoTimer
Collaborators are most welcomed for extending the project.
