### ISSUE TITLE
Lack of description

### ISSUE THREAD

**Issue by Jamim** [KalleHallden/AutoTimer#3]
Hi there,

Congratulations, this projects is on the second line of [Trending Python repositories chart](https://github.com/trending/python?since=daily) now! :tada:
Could you please add some details about what the heck is this to the README? :smiley:

Thank you!

**Comment by amitjslearn** [comment]
> Hi there,
> 
> Congratulations, this projects is on the second line of [Trending Python repositories chart](https://github.com/trending/python?since=daily) now! 
> Could you please add some details about what the heck is this to the README? 
> 
> Thank you!
Check out now.
https://github.com/KalleHallden/AutoTimer/blob/8bef24773af4c046e4d17c06422535ceecbae209/README.md

**Comment by amitjslearn** [comment]
> Hi there,
> 
> Congratulations, this projects is on the second line of [Trending Python repositories chart](https://github.com/trending/python?since=daily) now! 
> Could you please add some details about what the heck is this to the README? 
> 
> Thank you!

check out the link below.
https://github.com/KalleHallden/AutoTimer/blob/8bef24773af4c046e4d17c06422535ceecbae209/README.md
